#ifndef BRIMEARSPOINT_HPP
#define BRIMEARSPOINT_HPP

#include <libslic3r/Point.hpp>


namespace Slic3r {

// 一个枚举，用于跟踪 ModelObject 上当前点的来源。
enum class PointsStatus {
    NoPoints,           // 到目前为止未生成任何点。
    Generating,     // 自动生成算法已触发，但尚未完成。
    AutoGenerated,  // 点已自动生成（即从后端复制）。
    UserModified    // 用户已完成一些编辑。
};

struct BrimPoint
{
    Vec3f pos;
    float head_front_radius;

    BrimPoint()
        : pos(Vec3f::Zero()), head_front_radius(0.f)
    {}

    BrimPoint(float pos_x,
                 float pos_y,
                 float pos_z,
                 float head_radius)
        : pos(pos_x, pos_y, pos_z)
        , head_front_radius(head_radius)
    {}

    BrimPoint(Vec3f position, float head_radius)
        : pos(position)
        , head_front_radius(head_radius)
    {}

    Vec3f transform(const Transform3d &trsf)
    {
        Vec3d result = trsf * pos.cast<double>();
        return result.cast<float>();
    }

    bool operator==(const BrimPoint &sp) const
    {
        float rdiff = std::abs(head_front_radius - sp.head_front_radius);
        return (pos == sp.pos) && rdiff < float(EPSILON);
    }

    bool operator!=(const BrimPoint &sp) const { return !(sp == (*this)); }
    template<class Archive> void serialize(Archive &ar)
    {
        ar(pos, head_front_radius);
    }
};

using BrimPoints = std::vector<BrimPoint>;

}


#endif // BRIMEARSPOINT_HPP